stages:
  - lint
  - test
  - build

test:
  stage: test

  image: elixir:latest

  services:
    - postgres:latest

  variables:
    POSTGRES_DB: hello_test
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"
    MIX_ENV: "test"

  before_script:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
    - mix ecto.create
    - mix ecto.migrate

  script:
    - mix test

lint:
  stage: lint
  allow_failure: true
  image: elixir:latest
  # use cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - _build
      - deps
  script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix format --check-formatted
    - mix credo --strict

compile:
  stage: build
  image: elixir:latest
  # use cache to speed up subsequent builds
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - _build
      - deps
  script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix compile --warnings-as-errors
