version: "3"
services:
  database:
    image: postgres:14
    environment:
      - DATABASE_URL=ecto://lehrstuhl-mgmt:lehrstuhl-mgmt@lehrstuhl-mgmt/lehrstuhl-mgmt
      - POSTGRES_USER=lehrstuhl-mgmt
      - POSTGRES_PASSWORD=lehrstuhl-mgmt
      - POSTGRES_DB=lehrstuhl-mgmt
    volumes:
      - local_pgdata:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin  
    ports:
      - "5050:80"
    depends_on:
      # The DB container needs to be started before we start this container.
      - database      
  # phoenix:
  #   build:
  #     # Here we define that it should build from the current directory.
  #     context: .
  #   environment:
  #     # Variables to connect to our Postgres server.
  #     DATABASE_URL: ecto://lehrstuhl-mgmt:lehrstuhl-mgmt@phoenix-test-semiar_database_1/lehrstuhl-mgmt
  #     SECRET_KEY_BASE: fIzX0WOin193X+6TZMXG/QSjXBK28XeR3zFTN9W6lvF2iGJ0u7YaCBI4jZHj4+wE
  #     PGUSER: lehrstuhl-mgmt
  #     PGPASSWORD: lehrstuhl-mgmt
  #     PGDATABASE: lehrstuhl-mgmt
  #     PGPORT: 5432
  #     # Hostname of our Postgres container.
  #     PGHOST: db
  #   ports:
  #     # Mapping the port to make the Phoenix app accessible outside of the container.
  #     - '4000:4000'
  #   depends_on:
  #     # The DB container needs to be started before we start this container.
  #     - database
  #     - pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
